import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/app/components/footer/Footer";
import { Metadata } from "next";
import styles from "./styles/MainContainer.module.css";
import Header from "@/app/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Filipinho",
  description: "Generated by create next app",
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Header />
      <div className={styles.container}>{children}</div>
      <Footer />
    </>
  );
};

export default RootLayout;
