import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/app/components/footer/Footer";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Filipinho",
  description: "Generated by create next app",
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
